### ISSUE TITLE
MSAL for xamarin forms ios project(visual studio)

### ISSUE THREAD

**Issue by ClayAchahui** [sthewissen/MSALSample#1]
(Sorry for my english)
Hi Steven. I'm new on xamarin and i've been crying with MSAL Auth with ios proyect because on android it works succesfully.
I checked your blog and i found litle diferences with i did it.
My question is if for run on iOS platform connected with mac is necesary i have a real device or just a iOS simulator...
Thanks.

**Comment by sthewissen** [comment]
I’ve built the entire blog post and app using the simulator.

**Comment by ClayAchahui** [comment]
Thanks for your response.
I'm working with visual studio for windows and i would like that you check my configurations:
**Azure AD**

-->Mobile and desktop applications(you did it with android and ios plataform).

**Visual studio for windows**

-->it is connected with mac.
-->it has a apple account with 1 certificate(iOS devepment) 0 profile provisioning.
-->iOS project. when i set automatic provisioning...
`
Syncing devices for "INSTITUTO DE EDUCACION SUPERIOR TECNOLOGICO PRIVADO DEL SUR" team...
Processing iPad devices...
Processing iPhone devices...
Processing iPod devices...
Processing Apple Watch devices...
Creating new iOS Development provisioning profile for VS Wildcard application...
There was an error while trying to automatically provision the project: 'There are no current IOS devices on this team matching the provided device IDs.'
`
-->MSAL works on android but on iOS not.

**Xcode**
it has a apple account; but i've noticed that another blogs xcode must have project. i'm confused.

**Comment by ClayAchahui** [comment]
i had to register a device iOS on apple account.

**Comment by shyammani** [comment]
> i had to register a device iOS on apple account.

Hi ClayAchahui, I am having exactly same steps followed and same issue.

Are you suggesting to register the simulator in Apple developer account? 
Here? - https://developer.apple.com/account/resources/devices/add

Please guide me. Thanks!
